% %% MyMainScript
%import mlreportgen.report.*
%R = Report('HarrisCornerDetector', 'pdf');
tic;
%% Your code here
%THE REPORT OUGHT TO BE GENERATED AS PER THE LATEST INSTRUCTION HAS BEEN
%TRIED BUT NOT BEING ABLE TO DO SO COMPLETELY. I'VE TRIED TO ADD IMAGES
%INTO THE REPORT, BUT IT GIVES AN ERROR ASIN THE ADD FUNCTION DOESN'T
%SUPPORT THE SYNTAX CONTRADICTING WHAT HAS BEEN GIVEN IN THE RELATED MATLAB
%EXAMPLES. ALSO, THIS REPORT GENERATION METHOD DOESN'T SEEM TO BE
%WELL-DOCUMENTED. SO, PLEASE RESORT TO THE PREVIOUS METHOD OF REPORT
%GENEARATION BY PUBLISHING WHICH SEEMS QUITE EASIER!!

myHarrisCornerDetector();
toc;
