%% MyMainScript

tic;
%% Your code here
IMG1 = imread("../data/barbara.png");
IMG2 = imread("../data/TEM.png");
IMG3 = imread("../data/canyon.png");
IMG4 = imread("../data/retina.png");
IMG4ref = imread("../data/retinaRef.png");
IMG5 = imread("../data/church.png");
IMG6 = imread("../data/chestXray.png");
IMG7 = imread("../data/statue.png");
threshold = 15;
myForegroundMask(IMG7, threshold);
IMG8 = imread("maskedimage.png");
%IMG9 = imread("binarymask.png");
myLinearContrastStretching(IMG1);
myLinearContrastStretching(IMG2);
myLinearContrastStretching(IMG3);
myLinearContrastStretching(IMG5);
myLinearContrastStretching(IMG6);
myLinearContrastStretching(IMG7);
myLinearContrastStretching(IMG8);
%myLinearContrastStretching(IMG9);
myHE(IMG1);
myHE(IMG2);
myHE(IMG3);
myHE(IMG5);
myHE(IMG6);
myHE(IMG8);
myHM(IMG4, IMG4ref);
window_size = 5;
epsilon = 0.05;
myCLAHE(IMG1, window_size, epsilon);
myCLAHE(IMG2, window_size, epsilon);
myCLAHE(IMG3, window_size, epsilon);
myCLAHE(IMG6, window_size, epsilon);
window_size = 15;
epsilon = 0.1;
myCLAHE(IMG1, window_size, epsilon);
myCLAHE(IMG2, window_size, epsilon);
myCLAHE(IMG3, window_size, epsilon);
myCLAHE(IMG6, window_size, epsilon);
window_size = 5;
epsilon = 0.05;
myCLAHE(IMG1, window_size, epsilon);
myCLAHE(IMG2, window_size, epsilon);
myCLAHE(IMG3, window_size, epsilon);
myCLAHE(IMG6, window_size, epsilon);
toc;
